server:
  port: 8000
spring:
  h2:
    console:
      enabled: true
      settings: 
        web-allow-others: true  	
  jpa: 
    hibernate: 
      ddl-auto: update 
wmtipp:
  admin:
    login: admin
    password: blub

---
spring:
  profiles: filedb
  datasource:
    url: jdbc:h2:file:c:\users\katz.bastian\test.db
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa.hibernate.ddl-auto: update
  